// <auto-generated />
using APARTMENT_API.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace APARTMENT_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608020733_CreateTblBuilding")]
    partial class CreateTblBuilding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APARTMENT_API.Model.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("NameEnglish");

                    b.Property<string>("NameKhmer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("NameKhmer");

                    b.HasKey("Id");

                    b.ToTable("TblBuilding");
                });
#pragma warning restore 612, 618
        }
    }
}
