// <auto-generated />
using System;
using APARTMENT_API.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace APARTMENT_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819023609_CreateSalaryTable")]
    partial class CreateSalaryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APARTMENT_API.Model.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("NameEnglish");

                    b.Property<string>("NameKhmer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("NameKhmer");

                    b.HasKey("Id");

                    b.ToTable("TblBuilding");
                });

            modelBuilder.Entity("APARTMENT_API.Model.ExpensType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("expensType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("expensType");

                    b.HasKey("Id");

                    b.ToTable("ExpensType");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Floors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuildingId")
                        .HasColumnType("number")
                        .HasColumnName("BuildingId");

                    b.Property<byte>("FloorNo")
                        .HasColumnType("number(3)")
                        .HasColumnName("FloorNo");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("TblFloors");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("ItemName");

                    b.Property<string>("NameKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("NameKh");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("Remark")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("Remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("TblItem");
                });

            modelBuilder.Entity("APARTMENT_API.Model.OrtherExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CreateDate");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DateTime");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ExpenseTypeId");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Image");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Note");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("TblortherExpens");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("positionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("positionName");

                    b.Property<string>("positionNameKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("positionNameKh");

                    b.Property<int?>("status")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("TblPosition");
                });

            modelBuilder.Entity("APARTMENT_API.Model.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("RoomTypeName");

                    b.Property<string>("RoomTypeNameKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("RoomTypeNameKh");

                    b.HasKey("Id");

                    b.ToTable("TblRoomType");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("createby")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("createby");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("DATE")
                        .HasColumnName("createdate");

                    b.Property<DateTime>("date")
                        .HasColumnType("DATE")
                        .HasColumnName("date");

                    b.Property<string>("note")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("note");

                    b.Property<decimal>("salary")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("salary");

                    b.Property<int>("staffId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("staffid");

                    b.HasKey("Id");

                    b.HasIndex("staffId");

                    b.ToTable("TblSalary");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("DATE")
                        .HasColumnName("createAt");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("createBy");

                    b.Property<DateTime?>("dob")
                        .IsRequired()
                        .HasColumnType("DATE")
                        .HasColumnName("dob");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("email");

                    b.Property<string>("identityNo")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("identityNo");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("name");

                    b.Property<string>("nameKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nameKh");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("phone");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("photo");

                    b.Property<int>("positionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("positionId");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("sex");

                    b.Property<int>("status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("positionId");

                    b.ToTable("TblStaff");
                });

            modelBuilder.Entity("APARTMENT_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasMaxLength(50)
                        .HasColumnType("number(1)")
                        .HasColumnName("Active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("TblUser");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Floors", b =>
                {
                    b.HasOne("APARTMENT_API.Model.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("APARTMENT_API.Model.OrtherExpense", b =>
                {
                    b.HasOne("APARTMENT_API.Model.ExpensType", "ExpensType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpensType");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Salary", b =>
                {
                    b.HasOne("APARTMENT_API.Model.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("APARTMENT_API.Model.Staff", b =>
                {
                    b.HasOne("APARTMENT_API.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("positionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
